coverage:
  status:
    project:
      gdscript:
        target: 70%
        paths: scripts/
        flags: gdscript
      javascript:
        target: 50%  # Explicit threshold for JS coverage
        paths: export/web/
        flags: playwright
  patch:
    default:
      target: 80%
comment:
  layout: "diff, files"
ignore:
  - export/web/*  # Still exclude JS from project total
flags:
  gdscript:
    paths:
      - scripts/
  playwright:
    paths:
      - export/web/
