coverage:
  status:
    project:
      gdscript:
        target: auto
        flags:
          - GDUnit4
        paths:
          - "scripts/"
    patch:
      default:
        target: 80%
  precision: 2
  round: down

comment:
  layout: "diff, files"

ignore:
  - "test/**/*"
  - "tests/**/*"
  - "addons/**/*"

flags:
  GDUnit4:
    paths:
      - "scripts/"

fixes:
  - "/home/runner/work/SkyLockAssault/SkyLockAssault/::"
