coverage:
  status:
    project:
      gdscript:
        target: auto
        flags:
          - GDUnit4
    patch:
      default:
        target: 80%
  precision: 2
  round: down

comment:
  layout: "diff, files"

ignore:
  - "tests/**/*"
  - "addons/**/*"

flags:
  GDUnit4:
    paths:
      - "scripts/"
      - "test/gdunit4/"
