coverage:
  status:
    project:
      gdscript:
        target: 70%
        paths:
          - scripts/
        flags:
          - gdscript
      javascript:
        target: 50%
        paths:
          - export/web/
        flags:
          - playwright
    patch:
      default:
        target: 80%
  precision: 2
  range: "60...90"
  round: down

comment:
  layout: "diff, files"

ignore:
  - export/web/*

flags:
  gdscript:
    paths:
      - scripts/
  playwright:
    paths:
      - export/web/

fixes:
  - "::export/web/"  # New: Strip empty prefixes
  - "anonymous_::export/web/index.js"  # Map anonymous to real JS file (adjust if multiple)
  - "/home/runner/work/SkyLockAssault/SkyLockAssault/::"  # Strip CI absolute paths
