services:
  godot_web_server:
    image: nginx:1.27-alpine  # Keep this; confirmed ~56 vulns, but we'll ignore below
    container_name: sky_lock_assault_server
    ports:
      - "127.0.0.1:9090:80"  # Local-only; good
    restart: unless-stopped
    volumes:
      - ../export/web:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx/conf.d
    user: "nginx:nginx"  # Non-root; good
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]  # CHANGED: Use netcat (nc) for TCP probe; Alpine has busybox nc built-in, no shell needed
      interval: 30s
      timeout: 10s
      retries: 3
