services:
  godot_web_server:
    image: nginx:1.27-alpine
    container_name: sky_lock_assault_server
    ports:
      - "127.0.0.1:9090:80"  # NEW: Restrict to localhost (your PC only); fixes exposed port errors
    restart: unless-stopped
    volumes:
      - ../export/web:/usr/share/nginx/html:ro  # Mount your Web export folder read-only
      - ./nginx:/etc/nginx/conf.d  # Mount custom Nginx config folder
    user: "nginx:nginx"  # NEW: Run as non-root user; fixes privilege escalation risks
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
