services:
  godot_web_server:
    image: nginx:latest
    container_name: sky_lock_assault_server
    ports:
      - "9090:80"  # Local port 9090 to container 80; change if conflicted (e.g., to 8080:80)
    restart: unless-stopped
    volumes:
      - ../export/web:/usr/share/nginx/html:ro  # Mount your Web export folder read-only
      - ./nginx:/etc/nginx/conf.d  # Mount custom Nginx config folder