---
name: "GDScript Lint and Format Check"

on:  # yamllint disable-line rule:truthy
  # Makes it reusable; called by other workflows
  workflow_call:  # yamllint disable rule:empty-values

jobs:
  review:
    name: "Lint and Format Check"
    runs-on: "ubuntu-latest"
    # Adding 'timeout-minutes: 10' would prevent jobs from running
    # indefinitely if something goes wrong
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.x"
      - name: "Cache PIP Dependencies"
        uses: "actions/cache@v4"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-gdtoolkit"
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Install GDToolkit (for gdlint & gdformat)"
        # Installs gdtoolkit==4.* for Godot 4.x
        uses: "Scony/godot-gdscript-toolkit@master"
      - name: "Check Formatting"
        # Scans all .gd files; use --diff for detailed output
        run: |
          gdformat --diff --check .
      - name: "Lint Code"
        # Runs static analysis; fails if issues found
        run: |
          gdlint .
