---
name: "Snyk Scan on Web Export"

on:  # yamllint disable-line rule:truthy
  # Makes it reusable; called by other workflows
  workflow_call:
    secrets:
      SNYK_TOKEN:
        description: "Snyk Auth Token"
        required: true

jobs:
  snyk:
    runs-on: "ubuntu-latest"
    # Adding 'timeout-minutes: 10' would prevent jobs from running
    # indefinitely if something goes wrong
    timeout-minutes: 10
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"  # Consistent with CodeQL

      - name: "List files in export/web (for visibility)"
        run: |
          echo "Files to be scanned in export/web:"
          ls -l export/web || echo "No files found—check if folder exists!"

      - name: "Set up Snyk"
        uses: "snyk/actions/setup@master"  # Pinned SHA for security

      - name: "Authenticate Snyk"
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: "Scan Code (SAST on export/web)"
        run: |
          snyk code test export/web --severity-threshold=medium -d --report  # -d for debug, --report for JSON if issues

      - name: "Scan Open Source (unmanaged deps in export/web)"
        run: |
          snyk test export/web --unmanaged --severity-threshold=high -d --report  # -d for debug, --report for JSON
