---
name: "Snyk Scan on Web Export"

on:  # yamllint disable-line rule:truthy
  # Makes it reusable; called by other workflows
  workflow_call:
    secrets:
      SNYK_TOKEN:
        description: "Snyk Auth Token"
        required: true

jobs:
  snyk:
    runs-on: "ubuntu-latest"
    # Adding 'timeout-minutes: 10' would prevent jobs from running
    # indefinitely if something goes wrong
    timeout-minutes: 10
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"  # Consistent with CodeQL

      - name: "List files in export/web (for visibility)"
        run: |
          echo "Files to be scanned in export/web:"
          ls -l export/web || echo "No files found—check if folder exists!"

      - name: "Set up Snyk"
        uses: "snyk/actions/setup@master"  # Properly pinned to SHA (v0.4.0) for security

      - name: "Authenticate Snyk"
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: "Scan Code (SAST on export/web)"
        run: |
          snyk code test export/web --severity-threshold=medium -d
        # Proceed if no supported files or low issues—learn from logs
        continue-on-error: true

      - name: "Scan Open Source (unmanaged deps in export/web)"
        # yamllint disable rule:line-length
        run: |
          snyk test export/web --unmanaged --severity-threshold=high -d --sarif-file-output=snyk-os.sarif
        continue-on-error: true

      - name: "Upload Snyk Open Source SARIF"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "snyk-os.sarif"
        if: always()

      - name: "Post-scan summary (optional)"
        if: always()  # Run even if previous steps fail
        # yamllint disable rule:line-length
        run: |
          echo "Snyk scan complete on export/web—results uploaded to Security > Code scanning tab. Check for alerts there or in logs."