---
name: "Snyk Scan on Web Export"

on:  # yamllint disable-line rule:truthy
  # Makes it reusable; called by other workflows
  workflow_call:
    secrets:
      SNYK_TOKEN:
        description: "Snyk Auth Token"
        required: true

jobs:
  snyk:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"  # For SARIF uploads to GitHub Security tab
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "List files in export/web (for visibility)"
        run: |
          echo "Files to be scanned in export/web:"
          ls -l export/web || echo "No files found—check if folder exists!"

      - name: "Set up Snyk"
        uses: "snyk/actions/setup@master"  # Pinned for security

      - name: "Authenticate Snyk"
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: "Scan Code (SAST on export/web)"
        # yamllint disable rule:line-length
        run: |
          snyk code test export/web --severity-threshold=medium -d --report --sarif-file-output=snyk-code.sarif
        continue-on-error: true

      - name: "Upload Snyk Code SARIF to GitHub"
        uses: "github/codeql-action/upload-sarif@v3"
        if: "always() && hashFiles('snyk-code.sarif') != ''"
        with:
          sarif_file: "snyk-code.sarif"

      - name: "Scan Open Source (unmanaged deps in export/web)"
        run: |
          snyk test export/web --unmanaged --severity-threshold=high -d --report --sarif-file-output=snyk-os.sarif
        continue-on-error: true

      - name: "Upload Snyk Open Source SARIF to GitHub"
        uses: "github/codeql-action/upload-sarif@v3"
        if: "always() && hashFiles('snyk-os.sarif') != ''"
        with:
          sarif_file: "snyk-os.sarif"

      - name: "Post-scan summary (optional)"
        if: "always()"
        run: |
          if [ -f snyk-code.sarif ] || [ -f snyk-os.sarif ]; then
            echo "Snyk scan complete on export/web—results uploaded to app.snyk.io dashboard (check Projects/Reports) and GitHub Security tab."
          else
            echo "Snyk scan complete on export/web—no supported files or vulnerabilities found. No results uploaded."
          fi