---
name: "Snyk Scan on Web Export"

on:  # yamllint disable-line rule:truthy
  # Makes it reusable; called by other workflows
  workflow_call:
    secrets:
      SNYK_TOKEN:
        description: "Snyk Auth Token"
        required: true

jobs:
  snyk:
    runs-on: "ubuntu-latest"
    # Adding 'timeout-minutes: 10' would prevent jobs from running
    # indefinitely if something goes wrong
    timeout-minutes: 10
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"  # Consistent with CodeQL

      - name: "List files in export/web (for visibility)"
        run: |
          echo "Files to be scanned in export/web:"
          ls -l export/web || echo "No files found—check if folder exists!"

      - name: "Set up Snyk"
        uses: "snyk/actions/setup@master"  # Properly pinned to SHA (v0.4.0) for security

      - name: "Authenticate Snyk"
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: "Scan Code (SAST on export/web)"
        run: |
          snyk code test export/web --severity-threshold=medium -d  # -d for debug logs; removed --report to avoid upload issues
        continue-on-error: true  # Proceed if no supported files or low issues—learn from logs

      - name: "Scan Open Source (unmanaged deps in export/web)"
        run: |
          snyk test export/web --unmanaged --severity-threshold=high -d  # -d for debug; removed --report
        continue-on-error: true  # Proceed if no deps found; change to false if you want strict fails on highs

      - name: "Post-scan summary (optional)"
        if: always()  # Run even if previous steps fail
        run: |
          echo "Snyk scan complete on export/web—check logs for details or Security tab if integrated."
