---
name: "Godot Unit Tests"

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: "Codecov requires a token to authenticate"
        required: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v5
      - name: "Verify Project Godot Version"
        run: |
          # Extract version from project.godot
          VERSION=$(grep '^godot_version' project.godot | cut -d'=' -f2 | tr -d '"' | tr -d "'")
          echo "Detected Godot version: $VERSION"
          if [[ ! "$VERSION" =~ ^4\.5 ]]; then
            echo "Warning: Version mismatch; forcing 4.5-stable for GdUnit4"
            echo "GODOT_VERSION=4.5-stable" >> $GITHUB_ENV
          fi
      - name: "Run GdUnit4 Tests"
        uses: MikeSchulze/gdunit4-action@v1
        with:
          godot_version: "4.5-stable"  # Override to match project
          test_suites: "res://test"    # Your test dir
          continue_on_failure: false   # Fail CI on test errors
      - name: "List Reports"
        run: |
          ls -la res/reports/
      - name: "Extract Coverage from HTML (for Codecov)"
        run: |
          python3 -c "
          import json
          import re
          try:
              with open('res/reports/index.html', 'r') as f:
                  html = f.read()
              match = re.search(r'id=\"coverage\"[^>]*>([0-9]+)%', html)
              coverage_pct = int(match.group(1)) if match else 0
              data = {'coverage': {'total': 100, 'covered': coverage_pct, 'pct': coverage_pct}}
              with open('res/reports/coverage.json', 'w') as f:
                  json.dump(data, f, indent=2)
              print(f'Extracted coverage: {coverage_pct}%')
          except FileNotFoundError:
              print('No index.html; skipping extraction')
          "
      - name: "Upload Coverage to Codecov"
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          files: ./res/reports/coverage.json,./res/reports/*.xml,./res/reports/index.html  # JSON + JUnit + HTML fallback
          flags: gdscript
          fail_ci_if_error: false  # Soften to avoid CI block if format issues
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: "Upload Test Reports Artifacts"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gdunit-reports
          path: res/reports/**
          retention-days: 5
