---
# yamllint disable-file rule:line-length
name: "Godot Unit Tests"

on:  # yamllint disable-line rule:truthy
  workflow_call:  # yamllint disable-line rule:empty-values

jobs:
  unit-test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    permissions:
      checks: "write"  # Add this to allow check run creation
    steps:
      - uses: "actions/checkout@v5"
      - name: "Download Godot Binary"
        run: |        
          wget https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          unzip Godot_v4.5-stable_linux.x86_64.zip
          mv Godot_v4.5-stable_linux.x86_64 godot
          chmod +x godot
      - name: "Install GDUnit4"
        run: |
          mkdir -p addons
          wget https://github.com/MikeSchulze/gdUnit4/archive/refs/tags/v6.0.0.zip
          unzip v6.0.0.zip -d addons
          mv addons/gdUnit4-6.0.0/addons/gdUnit4 addons/gdUnit4
          rm -rf addons/gdUnit4-6.0.0  # Cleanup
      - name: "Import Resources"
        run: |
          ./godot --headless --path . --import --quit
      - name: "Run GDUnit4 Tests"
        run: |
          ./godot --headless --path . -s res://addons/gdUnit4/bin/GdUnitCmdTool.gd --verbose --ignoreHeadlessMode --add res://test
      - name: "Upload Test Reports"
        if: "always()"  # Runs even on failure
        uses: "actions/upload-artifact@v4"
        with:
          name: "gdunit-reports"
          path: "reports/**"
          retention-days: 5  # Keep for 5 days
