---
name: "Godot Unit Tests"

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  unit-test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@v5"
      - name: "Install Xvfb"  # Manual install for virtual display
        run: |
          sudo apt update
          sudo apt install -y xvfb
      - name: "Setup Godot Headless"
        uses: "firebelley/godot-export@29965918cc35b77c465839035775e0e12dc87029"  # Pinned to commit SHA for v6.0.0
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot-builds/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz"
          cache: true
      - name: "Install GdUnit4"  # Manual install to addons (v5.1.1)
        run: |
          git clone --branch v5.1.1 --depth 1 https://github.com/MikeSchulze/gdUnit4 ./.install-gdunit4
          rm -rf ./.install-gdunit4/addons/gdUnit4/test  # Remove self-tests if not needed
          mkdir -p ./addons
          cp -R ./.install-gdunit4/addons/gdUnit4 ./addons
          chmod +x ./addons/gdUnit4/runtest.sh
      - name: "Run GdUnit4 Tests"  # Manual run with xvfb-run for headless
        run: |
          GODOT_BIN="/home/runner/.local/share/godot/godot_executable/Godot_v4.5-stable_linux.x86_64"
          xvfb-run --auto-servernum ./addons/gdUnit4/runtest.sh -a res://tests/
      - name: "Upload Test Results"
        if: always()
        uses: "actions/upload-artifact@v4"
        with:
          name: unit-test-results
          path: gdunit4-report.xml
