---
name: "Godot Unit Tests"

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  unit-test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    permissions:
      checks: write  # Add this to allow check run creation
    steps:
      - uses: "actions/checkout@v5"
      - name: "Install Xvfb"  # Manual install for virtual display
        run: |
          sudo apt update
          sudo apt install -y xvfb
      - name: "GdUnit4 - Test Runner Action"
        uses: "MikeSchulze/gdUnit4-action@7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1"  # Pinned to v1.1.6 SHA
        with:
          godot-version: '4.4'
          paths: 'res://test'
          timeout: 5              # Optional: Test timeout in minutes
          version: 'latest'       # Optional: GdUnit4 version
          arguments: '--verbose --ignoreHeadlessMode'
      - name: "Upload Test Reports"
        if: always()  # Runs even on failure
        uses: "actions/upload-artifact@v4"
        with:
          name: gdunit-reports
          path: reports/**
          retention-days: 5  # Keep for 5 days
