---
name: "Godot Unit Tests"

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  unit-test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@v5"
      - name: "Setup Xvfb"  # Added: Virtual display for headless CI
        uses: "coactions/setup-xvfb@v1"
      - name: "Setup Godot Headless"
        uses: "firebelley/godot-export@29965918cc35b77c465839035775e0e12dc87029"  # Pinned to commit SHA for v6.0.0
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot-builds/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz"
          cache: true
      - name: "Run GdUnit4 Tests"
        uses: "MikeSchulze/gdUnit4-action@a5b68eab7dd87974a2b44dc047685ff86fabfabb"  # Changed to v1 and pinned to commit SHA (latest in v1.x series)
        with:
          godot-version: '4.5'  # Added: Specifies Godot 4.5 (defaults to stable status)
          godot-status: 'stable'  # Added: Ensures correct download URL
          paths: "res://tests/"  # Your test folder
      - name: "Upload Test Results"
        if: always()
        uses: "actions/upload-artifact@v4"
        with:
          name: unit-test-results
          path: gdunit4-report.xml
