---
name: "Godot Unit Tests"

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  unit-test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@v5"
      - name: "Install Xvfb"  # Manual install for virtual display
        run: |
          sudo apt update
          sudo apt install -y xvfb
      - name: "GdUnit4 - Test Runner Action"
        uses: "MikeSchulze/gdUnit4-action@v1.1.6"
        with:
          godot-version: '4.5'
          paths: 'res://tests'
          timeout: 5              # Optional: Test timeout in minutes
          version: 'latest'       # Optional: GdUnit4 version
