---
name: "Godot Unit Tests"

on:  # yamllint disable-line rule:truthy
  workflow_call:  # yamllint disable-line rule:empty-values

jobs:
  unit-test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    permissions:
      checks: "write"  # Add this to allow check run creation
    steps:
      - uses: "actions/checkout@v5"
      - name: "Install Xvfb"  # Manual install for virtual display
        run: |
          sudo apt update
          sudo apt install -y xvfb
      - name: "GdUnit4 - Test Runner Action"
        # yamllint disable-line rule:line-length
        uses: "MikeSchulze/gdunit4-action@a5b68eab7dd87974a2b44dc047685ff86fabfabb"  # Correct SHA for v1.1.6
        with:
          godot-version: "4.5"
          paths: "res://test"
          timeout: 10             # Optional: Test timeout in minutes
          version: "latest"       # Optional: GdUnit4 version
          arguments: "--verbose"  # Remove --ignoreHeadlessMode
      - name: "Upload Test Reports"
        if: "always()"  # Runs even on failure
        uses: "actions/upload-artifact@v4"
        with:
          name: "gdunit-reports"
          path: "reports/**"
          retention-days: 5  # Keep for 5 days
