---
name: "Godot Unit Tests"

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: "Codecov requires a token to authenticate"
        required: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v5
      - name: "Run GdUnit4 Tests"
        id: gdunit
        uses: MikeSchulze/gdunit4-action@v1
        with:
          godot_version: "4.5-stable"  # Matches your project
          test_suites: "res://test"    # Your test dir
          continue_on_failure: false   # Fail CI on test errors
      - name: "List Reports"
        run: |
          ls -la res/reports/
      - name: "Extract Coverage from HTML (for Codecov)"
        run: |
          # Simple Python script to parse GdUnit4 HTML for coverage data
          # Assumes index.html has a <div id="coverage">70%</div> or similar; adjust selector if needed
          python3 -c "
          import json
          import re
          with open('res/reports/index.html', 'r') as f:
              html = f.read()
          # Example regex for coverage % (tune based on your HTML structure)
          match = re.search(r'id=\"coverage\"[^>]*>([0-9]+)%', html)
          coverage_pct = int(match.group(1)) if match else 0
          data = {'coverage': {'total': 100, 'covered': coverage_pct, 'pct': coverage_pct}}
          with open('res/reports/coverage.json', 'w') as f:
              json.dump(data, f, indent=2)
          print(f'Extracted coverage: {coverage_pct}%')
          "
      - name: "Upload Coverage to Codecov"
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          files: ./res/reports/coverage.json,./res/reports/*.xml  # JSON + JUnit fallback
          flags: gdscript
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: "Upload Test Reports Artifacts"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gdunit-reports
          path: res/reports/**
          retention-days: 5
